"use strict";

module.exports = {
	up: (queryInterface, Sequelize) => {
		return queryInterface.bulkInsert(
			"Cars",
			[
				// {
				// 	userId: 1,
				// 	carMake: "BMW",
				// 	carModel: "Z4 Roadster",
				// 	carYear: 2020,
				// 	pricePerDay: 149,
				// 	carImage:
				// 		"https://cache.bmwusa.com/cosy.arox?pov=walkaround&brand=WBBM&vehicle=21ZA&client=byo&paint=P0C10&fabric=FK8SW&sa=S01SU,S02TB,S0302,S0319,S0387,S03MB,S0430,S0431,S0459,S0465,S0493,S04AT,S04AW,S0534,S0544,S05AC,S0676,S06AC,S06AK,S06C4,S06U3,S0711,S07AC&date=20200702&angle=40&quality=65&sharp=100&resp=png&BKGND=TRANSPARENT&width=1279",
				// 	countryName: "United States",
				// 	stateName: "Nevada",
				// 	cityName: "Las Vegas",
				// 	address: "1554 N Christy Ln",
				// 	seats: 2,
				// 	electric: "no",
				// 	autonomous: "no",
				// 	roadsideAssistance: "yes",
				// },
				{
					userId: 1,
					carMake: "BMW",
					carModel: "Z4 Roadster",
					carYear: 2020,
					pricePerDay: 800,
					carImage:
						"https://cache.bmwusa.com/cosy.arox?pov=walkaround&brand=WBBM&vehicle=21ZA&client=byo&paint=P0C10&fabric=FK8SW&sa=S01SU,S02TB,S0302,S0319,S0387,S03MB,S0430,S0431,S0459,S0465,S0493,S04AT,S04AW,S0534,S0544,S05AC,S0676,S06AC,S06AK,S06C4,S06U3,S0711,S07AC&date=20200702&angle=40&quality=65&sharp=100&resp=png&BKGND=TRANSPARENT&width=1279",
					countryName: "United States",
					stateName: "Nevada",
					cityName: "Las Vegas",
					address: "1554 N Christy Ln",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "yes",
				},
				{
					userId: 2,
					carMake: "Porsche",
					carModel: "Taycan",
					carYear: 2019,
					pricePerDay: 1000,
					carImage:
						"https://images.hgmsites.net/hug/2020-porsche-taycan_100714579_h.jpg",
					countryName: "United States",
					stateName: "Nevada",
					cityName: "Las Vegas",
					address: "3742 Horseshoe Mesa St",
					seats: 5,
					electric: "yes",
					autonomous: "no",
					roadsideAssistance: "no",
				},
				{
					userId: 1,
					carMake: "Ferrari",
					carModel: "F8 Spider",
					carYear: 2020,
					pricePerDay: 1500,
					carImage:
						"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ferrari-f8-spider-front-1567969463.jpg?crop=0.744xw:0.527xh;0.109xw,0.257xh&resize=980:*",
					countryName: "United States",
					stateName: "Nevada",
					cityName: "Las Vegas",
					address: "8812 Harwich Ave",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "yes",
				},
				{
					userId: 2,
					carMake: "Brabham",
					carModel: "BT62",
					carYear: 2021,
					pricePerDay: 1960,
					carImage:
						"https://gtspirit.com/wp-content/uploads/2019/01/Brabham-BT62-Offered-With-Road-Legal-Option2.jpg",
					countryName: "United States",
					stateName: "Nevada",
					cityName: "Las Vegas",
					address: "1827 W Gowan Rd",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "no",
				},
				{
					userId: 1,
					carMake: "Lamborghini",
					carModel: "Sian FKP 37",
					carYear: 2021,
					pricePerDay: 2000,
					carImage:
						"https://static0.hotcarsimages.com/wordpress/wp-content/uploads/2021/01/Sian_1.jpg?q=50&fit=crop&w=960&h=500",
					countryName: "United States",
					stateName: "Nevada",
					cityName: "North Las Vegas",
					address: "816 Camden Yard Ct",
					seats: 2,
					electric: "hybrid",
					autonomous: "yes",
					roadsideAssistance: "yes",
				},
				{
					userId: 2,
					carMake: "BMW",
					carModel: "i8 Roadster",
					carYear: 2018,
					pricePerDay: 800,
					carImage:
						"https://www.autoguide.com/blog/wp-content/gallery/2018-bmw-i8-roadster-review-live-photos/2018-BMW-i8-Roadster-Review-7.JPG",
					countryName: "United States",
					stateName: "California",
					cityName: "Los Angeles",
					address: "5960 W 85th Pl",
					seats: 2,
					electric: "hybrid",
					autonomous: "no",
					roadsideAssistance: "no",
				},
				{
					userId: 1,
					carMake: "Lamborghini",
					carModel: "Avendator SVJ Roadster",
					carYear: 2020,
					pricePerDay: 2500,
					carImage:
						"https://www.bentleygoldcoast.com/galleria_images/8329/8329_p2_l.jpg",
					countryName: "United States",
					stateName: "California",
					cityName: "Los Angeles",
					address: "8500 Beverly 6692 Blvd",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "yes",
				},
				{
					userId: 2,
					carMake: "Ferrari",
					carModel: "458 Spider",
					carYear: 2019,
					pricePerDay: 1500,
					carImage:
						"https://cdn.carbuzz.com/gallery-images/840x560/398000/200/398262.jpg",
					countryName: "United States",
					stateName: "California",
					cityName: "Los Angeles",
					address: "3215 Overland Ave",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "no",
				},
				{
					userId: 1,
					carMake: "Bugatti",
					carModel: "Chiron Pur Sport",
					carYear: 2021,
					pricePerDay: 2100,
					carImage:
						"https://cdn.motor1.com/images/mgl/B37je/s3/2021-bugatti-chiron-pur-sport-front-quarter.jpg",
					countryName: "United States",
					stateName: "California",
					cityName: "Los Angeles",
					address: "4600 Rodeo Ln",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "yes",
				},
				{
					userId: 2,
					carMake: "Porsche",
					carModel: "Boxster 25 Year Anniversary Addition",
					carYear: 2021,
					pricePerDay: 2500,
					carImage:
						"https://car-images.bauersecure.com/pagefiles/100248/boxster_200.jpg",
					countryName: "United States",
					stateName: "California",
					cityName: "Los Angeles",
					address: "1000 S Westgate Ave",
					seats: 2,
					electric: "no",
					autonomous: "no",
					roadsideAssistance: "no",
				},
			],
			{}
		);
	},

	down: (queryInterface, Sequelize) => {
		return queryInterface.bulkDelete("Cars", null, {});
	},
};
